version: "3.9"

services:
  certbot:
    container_name: "certbot"
    image: certbot/dns-cloudflare:latest
    command: renew --dns-cloudflare
    volumes:
      - /docker/etc/letsencrypt:/etc/letsencrypt
      - /docker/var/lib/letsencrypt:/var/lib/letsencrypt
      - /docker/data/letsencrypt:/data/letsencrypt
      - /docker/var/log/letsencrypt:/var/log/letsencrypt

  certbot-restarter:
    container_name: "certbot-restarter"
    image: docker
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    command: ["/bin/sh", "-c", "while true; do sleep 60; docker restart certbot; done"]
    restart: unless-stopped